### PR TITLE
Fix supported region logic

### LINKED ISSUE #6: Ensure region is in whitelist
The regions Rekognition is available in have increased dramatically. We change the hardcoded value to a default and check if the defined region constant is in the current whitelist instead.

### PR DESCRIPTION
**Pull request by roborourke**
The logic around checking supported regions wasn't right unfortunately.

Actually fixes #6 

- We weren't checking the region set when creating the client so an unsupported region could be passed when relying on the instance profile
- Using the S3 object params requires that the Rekognition client has the same region as the S3 bucket

I think this fixes the root of the problem by adding in compatibility with S3 uploads for the default region and comparing rekog client region to S3 region.

This relies on using S3 uploads, or at least having `S3_UPLOADS_REGION` defined, if we were to avoid that requirement however a more robust solution would be to check the bucket region based on the given attachment file URL but that's not 100% either. Thoughts?

### CODE REVIEW

File: inc/namespace.php [hunk 1]
```diff
@@ -328,15 +343,25 @@ function get_rekognition_client() : RekognitionClient {
...
+	if ( defined( 'S3_UPLOADS_REGION' ) ) {
+		$client_args['region'] = S3_UPLOADS_REGION;
+	}
 	if ( defined( 'AWS_REKOGNITION_REGION' ) ) {
 		$client_args['region'] = AWS_REKOGNITION_REGION;
 	}
 
-	if ( defined( 'AWS_REKOGNITION_KEY' ) && defined( 'AWS_REKOGNITION_SECRET' ) && defined( 'AWS_REKOGNITION_REGION' ) ) {
+	// Ensure region is supported.
+	if ( ! in_array( $client_args['region'], get_supported_regions(), true ) ) {
```
Comment (rmccue) [inline inc/namespace.php:355]: Should we also warn? 🤔

File: inc/namespace.php [hunk 2]
```diff
@@ -328,15 +343,25 @@ function get_rekognition_client() : RekognitionClient {
...
+		$client_args['region'] = 'us-east-1';
+	}
+
+	// Use credentials if provided.
+	if ( defined( 'AWS_REKOGNITION_KEY' ) && defined( 'AWS_REKOGNITION_SECRET' ) ) {
 		$client_args['credentials'] = [
 			'key'    => AWS_REKOGNITION_KEY,
 			'secret' => AWS_REKOGNITION_SECRET,
-			'region' => AWS_REKOGNITION_REGION,
+			'region' => $client_args['region'],
```
Comment (rmccue) [inline inc/namespace.php:365]: Will this get set if the instance profile is used instead of the constants?

Comment (roborourke) [reply inc/namespace.php:365]: It defaults to `us-east-1` above

Comment (roborourke) [reply inc/namespace.php:365]: Sorry I see what you mean. The instance profile as far as I can tell has access to Rekognition on any region, at least on our stack so presumably it'd use the client's region when authenticating requests but need to confirm that.

**Review by rmccue — APPROVED** [review]

File: inc/namespace.php (hunk 2 above)
Comment (nathanielks) [reply inc/namespace.php:365]: @roborourke 	correct, when using instance profiles, the client will use whatever region the SDK client is instantiated with. The SDK will then attempt to authenticate using Instance Profiles, IAM Task Roles, etc when an explicit key/secret pair is not provided to the client.

Comment (nathanielks) [reply inc/namespace.php:365]: Also, fwiw, the `Client::factory` pattern was deprecated in v3 of their SDK: https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/getting-started_migration.html#client-instantiation-uses-the-constructor

**Review by joehoyle — APPROVED** [review]
